version: '3.5'
services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: test_for_vita_soft2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
